import pytest
import chromadb
from app.rag.ingestion import setup_chroma_collection, CURATED_MODULES
from app.rag.retrieval import ChromaRetriever
from app.education.llm import MockLLM
from app.education.service import EducationService
from app.contracts.output import PersonCResponse

@pytest.fixture
def test_collection():
    client = chromadb.EphemeralClient()
    return setup_chroma_collection(client, "test_collection")

@pytest.fixture
def retriever(test_collection):
    return ChromaRetriever(test_collection)

@pytest.fixture
def education_service(retriever):
    return EducationService(retriever, MockLLM())

# RAG INGESTION
def test_rag_ingestion_loads_documents(test_collection):
    # 1. Knowledge documents can be loaded.
    assert test_collection.count() == 6

def test_rag_ingestion_modules_represented(test_collection):
    # 2. All three modules are represented: Money Map, Saving & Goals, Loans
    # 3. Chunks contain source metadata.
    # 4. Ingestion is repeatable/deterministic enough for tests.
    # 5. No chunk loses its module/source metadata.
    result = test_collection.get()
    modules = set(m["module"] for m in result["metadatas"])
    assert modules == {"Saving & Goals", "Loans", "Money Management"}
    assert all("source_class" in m for m in result["metadatas"])

# RAG RETRIEVAL
# RAG RETRIEVAL
def test_rag_retrieval_money_management(retriever):
    # Tests semantic matching for money management
    contexts = retriever.retrieve("How can I manage my income and expenses?")
    assert len(contexts) > 0
    assert contexts[0].metadata["module"] == "Money Management"
    assert "source_class" in contexts[0].metadata

def test_rag_retrieval_saving_goals(retriever):
    # Tests semantic matching for savings goals
    contexts = retriever.retrieve("What is a savings goal?")
    assert len(contexts) > 0
    assert contexts[0].metadata["module"] == "Saving & Goals"
    
    contexts2 = retriever.retrieve("How should I plan my education savings?")
    assert len(contexts2) > 0
    assert contexts2[0].metadata["module"] == "Saving & Goals"

def test_rag_retrieval_loans(retriever):
    # Tests semantic matching for loans
    contexts = retriever.retrieve("Should I take a loan?")
    assert len(contexts) > 0
    assert contexts[0].metadata["module"] == "Loans"
    
    contexts2 = retriever.retrieve("What should I check before taking a loan?")
    assert len(contexts2) > 0
    assert contexts2[0].metadata["module"] == "Loans"

def test_rag_retrieval_unrelated(retriever):
    # Empty/unrelated retrieval safety
    contexts = retriever.retrieve("How to bake a cake?")
    assert len(contexts) > 0

# SOURCE GROUNDING & EDUCATION MODE
def test_education_mode_success(education_service):
    # 13. source_class comes from actual retrieved metadata.
    # 14. The system does not invent source attribution.
    # 17. Education Mode returns a valid PersonCResponse.
    # 18. mode == "education".
    # 19. response_text is non-empty for a successful grounded query.
    # 20. The correct source_class is returned.
    # 21. Disclaimer behavior is validated according to the existing project contract.
    # 22. Education Mode does not accidentally use personalized financial-state logic.
    resp = education_service.get_guidance("What is a money map?")
    assert isinstance(resp, PersonCResponse)
    assert resp.mode == "education"
    assert resp.source_class == "SEBI"
    assert "Based on the provided context:" in resp.response_text
    assert resp.disclaimer is True

def test_education_mode_grounding_content(education_service):
    # 15. The education response includes only knowledge supported by the retrieved context in the mocked LLM test.
    # 16. Named financial-product recommendations are not generated by the configured prompt/validation path.
    resp = education_service.get_guidance("What should I check before taking a loan?")
    assert "Based on the provided context:" in resp.response_text
    assert "HDFC" not in resp.response_text  # No named products

# LLM FAILURE
def test_llm_failure_handled_gracefully(retriever):
    # 23. Mock LLM failure is handled gracefully.
    failing_llm = MockLLM(simulate_failure=True)
    svc = EducationService(retriever, failing_llm)
    resp = svc.get_guidance("What is saving?")
    assert resp.response_text == "Sorry, I am currently unable to process your request."
    assert resp.source_class == "system"

def test_empty_llm_output_rejected(retriever):
    # 24. Empty LLM output cannot produce a valid successful response.
    # 25. Malformed LLM output is rejected/handled safely.
    empty_llm = MockLLM(simulate_malformed=True)
    svc = EducationService(retriever, empty_llm)
    resp = svc.get_guidance("What is saving?")
    assert resp.response_text == "Sorry, I encountered an error generating a response."
    assert resp.source_class == "system"
